// Generated by scripts/sat64_generator/gen_fp_sat64.py -- do not edit by hand.
// p = 0x13cfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff (637 bits, 10 limbs)

#include <fp.h>
#include <encoded_sizes.h>
#include <util_64.h>

#include <stddef.h>
#include <stdint.h>
#include <string.h>

#define FP_LIMBS 10
#define FP_BITS 637
#define FP_DECODE_REDUCE_CHUNK 72

_Static_assert(NWORDS_FIELD == FP_LIMBS, "NWORDS_FIELD does not match this prime");
_Static_assert(FP_ENCODED_BYTES == 80, "FP_ENCODED_BYTES does not match this prime");
_Static_assert(sizeof(digit_t) == sizeof(uint64_t), "the sat64 gf backend needs RADIX == 64");

static const uint64_t FP_MODULUS[FP_LIMBS] = { UINT64_C(0xffffffffffffffff), UINT64_C(0xffffffffffffffff), UINT64_C(0xffffffffffffffff), UINT64_C(0xffffffffffffffff), UINT64_C(0xffffffffffffffff), UINT64_C(0xffffffffffffffff), UINT64_C(0xffffffffffffffff), UINT64_C(0xffffffffffffffff), UINT64_C(0xffffffffffffffff), UINT64_C(0x13cfffffffffffff) };
static const uint64_t FP_P1 = UINT64_C(0x000000009e7fffff);
static const uint64_t FP_P1DIV_M = UINT64_C(0x9d79f179525582c9);
static const fp_t FP_ONE = { .limb = { UINT64_C(0x000000000000000c), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x1240000000000000) } };
static const fp_t FP_R2_ELEM = { .limb = { UINT64_C(0x751908e21eb00d92), UINT64_C(0xfa58d532e081361b), UINT64_C(0x7853fcc50c1d1292), UINT64_C(0x47dfb27922b9bdc7), UINT64_C(0xbcf8bb5b4169cab3), UINT64_C(0xb751908e21eb00ce), UINT64_C(0x2fa58d532e081361), UINT64_C(0x77853fcc50c1d129), UINT64_C(0x347dfb27922b9bdc), UINT64_C(0x0f2f8bb5b4169cab) } };
static const fp_t FP_TDEC_ELEM = { .limb = { UINT64_C(0xfa58d532e081361b), UINT64_C(0x7853fcc50c1d1292), UINT64_C(0x47dfb27922b9bdc7), UINT64_C(0xbcf8bb5b4169cab3), UINT64_C(0xb751908e21eb00ce), UINT64_C(0x2fa58d532e081361), UINT64_C(0x77853fcc50c1d129), UINT64_C(0x347dfb27922b9bdc), UINT64_C(0xebcf8bb5b4169cab), UINT64_C(0x091000000000000c) } };
static const uint64_t FP_SQRT_EXP[FP_LIMBS] = { UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x04f4000000000000) };
static const uint64_t FP_P_MINUS_3_DIV_FOUR[FP_LIMBS] = { UINT64_C(0xffffffffffffffff), UINT64_C(0xffffffffffffffff), UINT64_C(0xffffffffffffffff), UINT64_C(0xffffffffffffffff), UINT64_C(0xffffffffffffffff), UINT64_C(0xffffffffffffffff), UINT64_C(0xffffffffffffffff), UINT64_C(0xffffffffffffffff), UINT64_C(0xffffffffffffffff), UINT64_C(0x04f3ffffffffffff) };
static const size_t FP_NUM1 = 40;
static const size_t FP_NUM2 = 32;
static const fp_t FP_TFIXDIV = { .limb = { UINT64_C(0x809f53b797fe57fa), UINT64_C(0x09e08b7142964a4f), UINT64_C(0xc6db131cb94bf295), UINT64_C(0x376c0229bd8acdc1), UINT64_C(0xad097dcf4a5942fa), UINT64_C(0xc7a4d7a385596a76), UINT64_C(0xeec03cc2ee08b85c), UINT64_C(0x8deb40bdab0600b8), UINT64_C(0x1e0c8fb23b48ca3f), UINT64_C(0x034488141ad793b1) } };
static const fp_t FP_THREE_INV = { .limb = { UINT64_C(0xaaaaaaaaaaaaaaae), UINT64_C(0xaaaaaaaaaaaaaaaa), UINT64_C(0xaaaaaaaaaaaaaaaa), UINT64_C(0xaaaaaaaaaaaaaaaa), UINT64_C(0xaaaaaaaaaaaaaaaa), UINT64_C(0xaaaaaaaaaaaaaaaa), UINT64_C(0xaaaaaaaaaaaaaaaa), UINT64_C(0xaaaaaaaaaaaaaaaa), UINT64_C(0xaaaaaaaaaaaaaaaa), UINT64_C(0x134aaaaaaaaaaaaa) } };

const fp_t ZERO = { .limb = { 0 } };
const fp_t ONE = { .limb = { UINT64_C(0x000000000000000c), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x0000000000000000), UINT64_C(0x1240000000000000) } };

inline void
fp_set_zero(fp_t *x)
{
    for (size_t i = 0; i < FP_LIMBS; i++)
        x->limb[i] = 0;
}

inline void
fp_set_one(fp_t *x)
{
    *x = FP_ONE;
}

inline void
fp_copy(fp_t *a, const fp_t *b)
{
    uint64_t t0 = b->limb[0];
    uint64_t t1 = b->limb[1];
    uint64_t t2 = b->limb[2];
    uint64_t t3 = b->limb[3];
    uint64_t t4 = b->limb[4];
    uint64_t t5 = b->limb[5];
    uint64_t t6 = b->limb[6];
    uint64_t t7 = b->limb[7];
    uint64_t t8 = b->limb[8];
    uint64_t t9 = b->limb[9];
    a->limb[0] = t0;
    a->limb[1] = t1;
    a->limb[2] = t2;
    a->limb[3] = t3;
    a->limb[4] = t4;
    a->limb[5] = t5;
    a->limb[6] = t6;
    a->limb[7] = t7;
    a->limb[8] = t8;
    a->limb[9] = t9;
}

inline void
fp_set_small(fp_t *x, const digit_t val)
{
    fp_mul_small(x, &FP_ONE, (uint32_t)val);
}

inline void
fp_add(fp_t *r, const fp_t *a, const fp_t *b)
{
    uint64_t t0, t1, t2, t3, t4, t5, t6, t7, t8, t9;
    unsigned char c1 = 0;
    unsigned char c2 = 0;

    c1 = addcarry_u64(c1, a->limb[0], b->limb[0], &t0);
    c1 = addcarry_u64(c1, a->limb[1], b->limb[1], &t1);
    c1 = addcarry_u64(c1, a->limb[2], b->limb[2], &t2);
    c1 = addcarry_u64(c1, a->limb[3], b->limb[3], &t3);
    c1 = addcarry_u64(c1, a->limb[4], b->limb[4], &t4);
    c1 = addcarry_u64(c1, a->limb[5], b->limb[5], &t5);
    c1 = addcarry_u64(c1, a->limb[6], b->limb[6], &t6);
    c1 = addcarry_u64(c1, a->limb[7], b->limb[7], &t7);
    c1 = addcarry_u64(c1, a->limb[8], b->limb[8], &t8);
    c1 = addcarry_u64(c1, a->limb[9], b->limb[9], &t9);

    c2 = subborrow_u64(c2, t0, FP_MODULUS[0], &t0);
    c2 = subborrow_u64(c2, t1, FP_MODULUS[1], &t1);
    c2 = subborrow_u64(c2, t2, FP_MODULUS[2], &t2);
    c2 = subborrow_u64(c2, t3, FP_MODULUS[3], &t3);
    c2 = subborrow_u64(c2, t4, FP_MODULUS[4], &t4);
    c2 = subborrow_u64(c2, t5, FP_MODULUS[5], &t5);
    c2 = subborrow_u64(c2, t6, FP_MODULUS[6], &t6);
    c2 = subborrow_u64(c2, t7, FP_MODULUS[7], &t7);
    c2 = subborrow_u64(c2, t8, FP_MODULUS[8], &t8);
    c2 = subborrow_u64(c2, t9, FP_MODULUS[9], &t9);

    uint64_t mask = (uint64_t)c1 - (uint64_t)c2;
    unsigned char carry = 0;
    carry = addcarry_u64(carry, t0, (FP_MODULUS[0] & mask), &t0);
    carry = addcarry_u64(carry, t1, (FP_MODULUS[1] & mask), &t1);
    carry = addcarry_u64(carry, t2, (FP_MODULUS[2] & mask), &t2);
    carry = addcarry_u64(carry, t3, (FP_MODULUS[3] & mask), &t3);
    carry = addcarry_u64(carry, t4, (FP_MODULUS[4] & mask), &t4);
    carry = addcarry_u64(carry, t5, (FP_MODULUS[5] & mask), &t5);
    carry = addcarry_u64(carry, t6, (FP_MODULUS[6] & mask), &t6);
    carry = addcarry_u64(carry, t7, (FP_MODULUS[7] & mask), &t7);
    carry = addcarry_u64(carry, t8, (FP_MODULUS[8] & mask), &t8);
    carry = addcarry_u64(carry, t9, (FP_MODULUS[9] & mask), &t9);
    (void)carry;

    r->limb[0] = t0;
    r->limb[1] = t1;
    r->limb[2] = t2;
    r->limb[3] = t3;
    r->limb[4] = t4;
    r->limb[5] = t5;
    r->limb[6] = t6;
    r->limb[7] = t7;
    r->limb[8] = t8;
    r->limb[9] = t9;
}

inline void
fp_sub(fp_t *r, const fp_t *a, const fp_t *b)
{
    uint64_t t0, t1, t2, t3, t4, t5, t6, t7, t8, t9;
    unsigned char borrow = 0;

    borrow = subborrow_u64(borrow, a->limb[0], b->limb[0], &t0);
    borrow = subborrow_u64(borrow, a->limb[1], b->limb[1], &t1);
    borrow = subborrow_u64(borrow, a->limb[2], b->limb[2], &t2);
    borrow = subborrow_u64(borrow, a->limb[3], b->limb[3], &t3);
    borrow = subborrow_u64(borrow, a->limb[4], b->limb[4], &t4);
    borrow = subborrow_u64(borrow, a->limb[5], b->limb[5], &t5);
    borrow = subborrow_u64(borrow, a->limb[6], b->limb[6], &t6);
    borrow = subborrow_u64(borrow, a->limb[7], b->limb[7], &t7);
    borrow = subborrow_u64(borrow, a->limb[8], b->limb[8], &t8);
    borrow = subborrow_u64(borrow, a->limb[9], b->limb[9], &t9);

    uint64_t mask = (uint64_t)0 - borrow;
    unsigned char carry = 0;
    carry = addcarry_u64(carry, t0, (FP_MODULUS[0] & mask), &t0);
    carry = addcarry_u64(carry, t1, (FP_MODULUS[1] & mask), &t1);
    carry = addcarry_u64(carry, t2, (FP_MODULUS[2] & mask), &t2);
    carry = addcarry_u64(carry, t3, (FP_MODULUS[3] & mask), &t3);
    carry = addcarry_u64(carry, t4, (FP_MODULUS[4] & mask), &t4);
    carry = addcarry_u64(carry, t5, (FP_MODULUS[5] & mask), &t5);
    carry = addcarry_u64(carry, t6, (FP_MODULUS[6] & mask), &t6);
    carry = addcarry_u64(carry, t7, (FP_MODULUS[7] & mask), &t7);
    carry = addcarry_u64(carry, t8, (FP_MODULUS[8] & mask), &t8);
    carry = addcarry_u64(carry, t9, (FP_MODULUS[9] & mask), &t9);
    (void)carry;

    r->limb[0] = t0;
    r->limb[1] = t1;
    r->limb[2] = t2;
    r->limb[3] = t3;
    r->limb[4] = t4;
    r->limb[5] = t5;
    r->limb[6] = t6;
    r->limb[7] = t7;
    r->limb[8] = t8;
    r->limb[9] = t9;
}

inline void
fp_neg(fp_t *r, const fp_t *a)
{
    uint64_t t0, t1, t2, t3, t4, t5, t6, t7, t8, t9;
    unsigned char borrow = 0;

    borrow = subborrow_u64(borrow, 0, a->limb[0], &t0);
    borrow = subborrow_u64(borrow, 0, a->limb[1], &t1);
    borrow = subborrow_u64(borrow, 0, a->limb[2], &t2);
    borrow = subborrow_u64(borrow, 0, a->limb[3], &t3);
    borrow = subborrow_u64(borrow, 0, a->limb[4], &t4);
    borrow = subborrow_u64(borrow, 0, a->limb[5], &t5);
    borrow = subborrow_u64(borrow, 0, a->limb[6], &t6);
    borrow = subborrow_u64(borrow, 0, a->limb[7], &t7);
    borrow = subborrow_u64(borrow, 0, a->limb[8], &t8);
    borrow = subborrow_u64(borrow, 0, a->limb[9], &t9);

    uint64_t mask = (uint64_t)0 - borrow;
    unsigned char carry = 0;
    carry = addcarry_u64(carry, t0, (FP_MODULUS[0] & mask), &t0);
    carry = addcarry_u64(carry, t1, (FP_MODULUS[1] & mask), &t1);
    carry = addcarry_u64(carry, t2, (FP_MODULUS[2] & mask), &t2);
    carry = addcarry_u64(carry, t3, (FP_MODULUS[3] & mask), &t3);
    carry = addcarry_u64(carry, t4, (FP_MODULUS[4] & mask), &t4);
    carry = addcarry_u64(carry, t5, (FP_MODULUS[5] & mask), &t5);
    carry = addcarry_u64(carry, t6, (FP_MODULUS[6] & mask), &t6);
    carry = addcarry_u64(carry, t7, (FP_MODULUS[7] & mask), &t7);
    carry = addcarry_u64(carry, t8, (FP_MODULUS[8] & mask), &t8);
    carry = addcarry_u64(carry, t9, (FP_MODULUS[9] & mask), &t9);
    (void)carry;

    r->limb[0] = t0;
    r->limb[1] = t1;
    r->limb[2] = t2;
    r->limb[3] = t3;
    r->limb[4] = t4;
    r->limb[5] = t5;
    r->limb[6] = t6;
    r->limb[7] = t7;
    r->limb[8] = t8;
    r->limb[9] = t9;
}

inline void
fp_half(fp_t *out, const fp_t *a)
{
    uint64_t t0, t1, t2, t3, t4, t5, t6, t7, t8, t9;
    uint64_t m = (uint64_t)0 - (a->limb[0] & 1u);
    unsigned char carry = 0;

    carry = addcarry_u64(carry, a->limb[0], (FP_MODULUS[0] & m), &t0);
    carry = addcarry_u64(carry, a->limb[1], (FP_MODULUS[1] & m), &t1);
    carry = addcarry_u64(carry, a->limb[2], (FP_MODULUS[2] & m), &t2);
    carry = addcarry_u64(carry, a->limb[3], (FP_MODULUS[3] & m), &t3);
    carry = addcarry_u64(carry, a->limb[4], (FP_MODULUS[4] & m), &t4);
    carry = addcarry_u64(carry, a->limb[5], (FP_MODULUS[5] & m), &t5);
    carry = addcarry_u64(carry, a->limb[6], (FP_MODULUS[6] & m), &t6);
    carry = addcarry_u64(carry, a->limb[7], (FP_MODULUS[7] & m), &t7);
    carry = addcarry_u64(carry, a->limb[8], (FP_MODULUS[8] & m), &t8);
    carry = addcarry_u64(carry, a->limb[9], (FP_MODULUS[9] & m), &t9);

    t0 = (t0 >> 1) | (t1 << 63);
    t1 = (t1 >> 1) | (t2 << 63);
    t2 = (t2 >> 1) | (t3 << 63);
    t3 = (t3 >> 1) | (t4 << 63);
    t4 = (t4 >> 1) | (t5 << 63);
    t5 = (t5 >> 1) | (t6 << 63);
    t6 = (t6 >> 1) | (t7 << 63);
    t7 = (t7 >> 1) | (t8 << 63);
    t8 = (t8 >> 1) | (t9 << 63);
    t9 = (t9 >> 1) | ((uint64_t)carry << 63);

    out->limb[0] = t0;
    out->limb[1] = t1;
    out->limb[2] = t2;
    out->limb[3] = t3;
    out->limb[4] = t4;
    out->limb[5] = t5;
    out->limb[6] = t6;
    out->limb[7] = t7;
    out->limb[8] = t8;
    out->limb[9] = t9;
}

inline uint32_t
fp_is_equal(const fp_t *a, const fp_t *b)
{
    uint64_t r = 0;
    for (size_t i = 0; i < FP_LIMBS; i++)
        r |= a->limb[i] ^ b->limb[i];

    return (uint32_t)(((r | (uint64_t)(0 - r)) >> 63) - 1);
}

inline uint32_t
fp_is_zero(const fp_t *a)
{
    uint64_t x = a->limb[0];

    for (size_t i = 1; i < FP_LIMBS; i++) {
        x |= a->limb[i];
    }

    x |= (uint64_t)(0 - x);

    uint64_t s = (uint64_t)(((int64_t)x) >> 63);
    return (uint32_t)(~s);
}

inline void
fp_select(fp_t *out, const fp_t *a, const fp_t *b, uint32_t ctl)
{
    uint64_t c = (uint64_t)ctl | ((uint64_t)ctl << 32);
    for (size_t i = 0; i < FP_LIMBS; i++) {
        uint64_t wa = a->limb[i];
        uint64_t wb = b->limb[i];
        out->limb[i] = wa ^ (c & (wa ^ wb));
    }
}

inline void
fp_cswap(fp_t *a, fp_t *b, uint32_t ctl)
{
    uint64_t c = (uint64_t)ctl | ((uint64_t)ctl << 32);
    for (size_t i = 0; i < FP_LIMBS; i++) {
        uint64_t wa = a->limb[i];
        uint64_t wb = b->limb[i];
        uint64_t wc = c & (wa ^ wb);
        a->limb[i] = wa ^ wc;
        b->limb[i] = wb ^ wc;
    }
}

static inline void
fp_cond_neg(fp_t *a, uint32_t ctl)
{
    fp_t neg;
    fp_neg(&neg, a);
    fp_select(a, a, &neg, ctl);
}

static inline void
fp_internal_reduce(fp_t *x)
{
    for (size_t i = 0; i < FP_LIMBS; i++) {
        uint64_t f = x->limb[0];
        uint64_t lo, cc;

        mul_add(&lo, &cc,
                        f, FP_MODULUS[0], x->limb[0]);

        for (size_t j = 1; j < FP_LIMBS; j++) {
            uint64_t hi;
            mul_add2(&lo, &hi,
                             f, FP_MODULUS[j],
                             x->limb[j], cc);
            x->limb[j - 1] = lo;
            cc = hi;
        }

        x->limb[FP_LIMBS - 1] = cc;
    }
}


inline void
fp_mul_small(fp_t *out, const fp_t *a, const uint32_t val)
{
    fp_t t = *a;
    int32_t k = (int32_t)val;

    /* Get the absolute value of k, while retaining its sign. */
    uint32_t sk = (uint32_t)((int64_t)k >> 31);
    uint32_t ak = (((uint32_t)k ^ sk) - sk);

    /* Compute the product over integers. */
    uint64_t lo, hi;
    mul_u64(&lo, &hi, t.limb[0], (uint64_t)ak);
    t.limb[0] = lo;
    for (size_t i = 1; i < FP_LIMBS; i++) {
        uint64_t d, ee;
        mul_add(&d, &ee, t.limb[i], (uint64_t)ak, hi);
        t.limb[i] = d;
        hi = ee;
    }

    /* Extract the top word of the unreduced product. */
    uint64_t x1;
    /* The shift pattern is selected at generation time to avoid invalid
       compile-time shift counts in other branches. */
    x1 = (hi << 35) | (t.limb[FP_LIMBS - 1] >> 29);

    /* Compute b = floor(x1 / P1) with the Granlund-Montgomery reciprocal. */
    uint64_t ignored, reciprocal;
    mul_u64(&ignored, &reciprocal, x1, FP_P1DIV_M);
    uint64_t bq = ((x1 - reciprocal) >> 1) + reciprocal;
    bq >>= 31;
    bq += (FP_P1 - bq) >> 63;

    /* Subtract bq * p from x. */
    uint64_t cc1 = 0;
    unsigned char cc2 = 0;
    for (size_t i = 0; i < FP_LIMBS; i++) {
        uint64_t d, ee;
        mul_add(&d, &ee, bq, FP_MODULUS[i], cc1);
        cc1 = ee;
        cc2 = subborrow_u64(cc2, t.limb[i], d, &t.limb[i]);
    }
    {
        uint64_t d;
        (void)subborrow_u64(cc2, hi, cc1, &d);
        hi = d;
    }

    /* Add p (at most twice) while the result is negative. */
    for (unsigned i = 0; i < 2; i++) {
        uint64_t m = sign_word(hi);
        unsigned char carry = 0;
        for (size_t j = 0; j < FP_LIMBS; j++)
            carry = addcarry_u64(carry, t.limb[j],
                                         m & FP_MODULUS[j], &t.limb[j]);
        hi += carry;
    }

    *out = t;
    fp_cond_neg(out, sk);
}

// fp_mul: implemented in <arch>/fp_asm.S

// fp_sqr: implemented in <arch>/fp_asm.S

static void
fp_n_sqr(fp_t *out, const fp_t *a, uint32_t n)
{
    fp_t t = *a;
    for (uint32_t i = 0; i < n; i++)
        fp_sqr(&t, &t);
    *out = t;
}

static inline void
fp_montylin(fp_t *out, const fp_t *u, const fp_t *v, uint64_t f, uint64_t g)
{
    uint64_t sf = sign_word(f);
    uint64_t af = (f ^ sf) - sf;
    uint64_t sg = sign_word(g);
    uint64_t ag = (g ^ sg) - sg;
    fp_t tu = *u, tv = *v, neg;
    fp_neg(&neg, u);
    for (size_t i = 0; i < FP_LIMBS; i++)
        tu.limb[i] ^= sf & (tu.limb[i] ^ neg.limb[i]);
    fp_neg(&neg, v);
    for (size_t i = 0; i < FP_LIMBS; i++)
        tv.limb[i] ^= sg & (tv.limb[i] ^ neg.limb[i]);

    uint64_t lo, cc;
    mul_x2(&lo, &cc, tu.limb[0], af, tv.limb[0], ag);
    out->limb[0] = lo;
    for (size_t i = 1; i < FP_LIMBS; i++) {
        uint64_t hi;
        mul_x2_add(&lo, &hi, tu.limb[i], af, tv.limb[i], ag, cc);
        out->limb[i] = lo;
        cc = hi;
    }
    uint64_t up = cc;

    uint64_t q = out->limb[0];
    uint64_t cc2;
    mul_add(&lo, &cc2, q, FP_MODULUS[0], out->limb[0]);
    for (size_t i = 1; i < FP_LIMBS; i++) {
        uint64_t hi;
        mul_add2(&lo, &hi, q, FP_MODULUS[i], out->limb[i], cc2);
        out->limb[i - 1] = lo;
        cc2 = hi;
    }
    unsigned char cc1 = addcarry_u64(0, up, cc2,
                                               &out->limb[FP_LIMBS - 1]);

    unsigned char borrow = 0;
    for (size_t i = 0; i < FP_LIMBS; i++)
        borrow = subborrow_u64(borrow, out->limb[i], FP_MODULUS[i], &out->limb[i]);

    uint64_t mask = (uint64_t)cc1 - (uint64_t)borrow;
    unsigned char carry = 0;
    for (size_t i = 0; i < FP_LIMBS; i++)
        carry = addcarry_u64(carry, out->limb[i], FP_MODULUS[i] & mask, &out->limb[i]);
    (void)carry;
}

static inline uint64_t
fp_lindiv31abs(fp_t *out, const fp_t *a, const fp_t *b, uint64_t f, uint64_t g)
{
    uint64_t sf = sign_word(f);
    uint64_t af = (f ^ sf) - sf;
    uint64_t sg = sign_word(g);
    uint64_t ag = (g ^ sg) - sg;
    unsigned char cc1 = 0, cc2 = 0;
    uint64_t cc3 = 0;

    for (size_t i = 0; i < FP_LIMBS; i++) {
        uint64_t aa, bb, d, hi;
        cc1 = subborrow_u64(cc1, a->limb[i] ^ sf, sf, &aa);
        cc2 = subborrow_u64(cc2, b->limb[i] ^ sg, sg, &bb);
        mul_x2_add(&d, &hi, aa, af, bb, ag, cc3);
        out->limb[i] = d;
        cc3 = hi;
    }

    uint64_t up = cc3 - (((uint64_t)0 - (uint64_t)cc1) & af)
                    - (((uint64_t)0 - (uint64_t)cc2) & ag);
    for (size_t i = 0; i + 1 < FP_LIMBS; i++)
        out->limb[i] = (out->limb[i] >> 31) | (out->limb[i + 1] << 33);
    out->limb[FP_LIMBS - 1] = (out->limb[FP_LIMBS - 1] >> 31) | (up << 33);

    uint64_t w = sign_word(up);
    unsigned char borrow = 0;
    for (size_t i = 0; i < FP_LIMBS; i++)
        borrow = subborrow_u64(borrow, out->limb[i] ^ w, w, &out->limb[i]);
    (void)borrow;
    return w;
}

static void
fp_inv_to(fp_t *out, const fp_t *x)
{
    fp_t a = *x;
    fp_t b = { { 0 } };
    for (size_t i = 0; i < FP_LIMBS; i++)
        b.limb[i] = FP_MODULUS[i];
    fp_t u = FP_ONE;
    fp_t v = { { 0 } };

    for (size_t outer = 0; outer < FP_NUM1; outer++) {
        uint64_t c_hi = UINT64_MAX, c_lo = UINT64_MAX;
        uint64_t a_hi = 0, a_lo = 0, b_hi = 0, b_lo = 0;
        for (size_t j = FP_LIMBS; j-- > 0;) {
            uint64_t aw = a.limb[j], bw = b.limb[j];
            a_hi ^= (a_hi ^ aw) & c_hi;
            a_lo ^= (a_lo ^ aw) & c_lo;
            b_hi ^= (b_hi ^ bw) & c_hi;
            b_lo ^= (b_lo ^ bw) & c_lo;
            c_lo = c_hi;
            uint64_t mw = aw | bw;
            c_hi &= ((mw | (uint64_t)(0 - mw)) >> 63) - 1;
        }

        unsigned s = (unsigned)__builtin_clzll(a_hi | b_hi);
        uint64_t xa = (a_hi << s) | ((a_lo >> 1) >> (63 - s));
        uint64_t xb = (b_hi << s) | ((b_lo >> 1) >> (63 - s));
        xa = (xa & UINT64_C(0xffffffff80000000)) | (a.limb[0] & UINT64_C(0x7fffffff));
        xb = (xb & UINT64_C(0xffffffff80000000)) | (b.limb[0] & UINT64_C(0x7fffffff));
        xa ^= c_lo & (xa ^ a.limb[0]);
        xb ^= c_lo & (xb ^ b.limb[0]);

        uint64_t fg0 = 1, fg1 = UINT64_C(1) << 32;
        for (unsigned k = 0; k < 31; k++) {
            uint64_t a_odd = (uint64_t)0 - (xa & 1);
            uint64_t d;
            unsigned char borrow = subborrow_u64(0, xa, xb, &d);
            uint64_t swap = a_odd & ((uint64_t)0 - (uint64_t)borrow);
            uint64_t t = swap & (xa ^ xb); xa ^= t; xb ^= t;
            t = swap & (fg0 ^ fg1); fg0 ^= t; fg1 ^= t;
            xa -= a_odd & xb;
            fg0 -= a_odd & fg1;
            xa >>= 1;
            fg1 <<= 1;
        }
        fg0 += UINT64_C(0x7fffffff7fffffff);
        fg1 += UINT64_C(0x7fffffff7fffffff);
        uint64_t f0 = (fg0 & UINT64_C(0xffffffff)) - UINT64_C(0x7fffffff);
        uint64_t g0 = (fg0 >> 32) - UINT64_C(0x7fffffff);
        uint64_t f1 = (fg1 & UINT64_C(0xffffffff)) - UINT64_C(0x7fffffff);
        uint64_t g1 = (fg1 >> 32) - UINT64_C(0x7fffffff);

        fp_t na, nb, nu, nv;
        uint64_t nega = fp_lindiv31abs(&na, &a, &b, f0, g0);
        uint64_t negb = fp_lindiv31abs(&nb, &a, &b, f1, g1);
        f0 = (f0 ^ nega) - nega; g0 = (g0 ^ nega) - nega;
        f1 = (f1 ^ negb) - negb; g1 = (g1 ^ negb) - negb;
        fp_montylin(&nu, &u, &v, f0, g0);
        fp_montylin(&nv, &u, &v, f1, g1);
        a = na; b = nb; u = nu; v = nv;
    }

    uint64_t xa = a.limb[0], xb = b.limb[0];
    uint64_t f0 = 1, g0 = 0, f1 = 0, g1 = 1;
    for (size_t k = 0; k < FP_NUM2; k++) {
        uint64_t a_odd = (uint64_t)0 - (xa & 1);
        uint64_t d;
        unsigned char borrow = subborrow_u64(0, xa, xb, &d);
        uint64_t swap = a_odd & ((uint64_t)0 - (uint64_t)borrow);
        uint64_t t = swap & (xa ^ xb); xa ^= t; xb ^= t;
        t = swap & (f0 ^ f1); f0 ^= t; f1 ^= t;
        t = swap & (g0 ^ g1); g0 ^= t; g1 ^= t;
        xa -= a_odd & xb;
        f0 -= a_odd & f1;
        g0 -= a_odd & g1;
        xa >>= 1;
        f1 <<= 1;
        g1 <<= 1;
    }

    fp_montylin(out, &u, &v, f1, g1);

    uint64_t z = 0;
    for (size_t i = 0; i < FP_LIMBS; i++) z |= x->limb[i];
    uint64_t mask = (uint64_t)0 - ((z | (uint64_t)(0 - z)) >> 63);
    for (size_t i = 0; i < FP_LIMBS; i++) out->limb[i] &= mask;
    fp_mul(out, out, &FP_TFIXDIV);
}

void
fp_inv(fp_t *x)
{
    fp_t t = *x;
    fp_inv_to(x, &t);
}

static int32_t
fp_legendre(const fp_t *x)
{
    /*
     * Same optimized binary GCD as inversion, but without the Bezout
     * coefficients. We can operate directly on Montgomery values because
     * R = 2^(64*N) is a square in GF(p).
     */
    fp_t a = *x;
    fp_t b = { { 0 } };
    for (size_t i = 0; i < FP_LIMBS; i++)
        b.limb[i] = FP_MODULUS[i];
    uint64_t ls = 0;

    for (size_t outer = 0; outer < FP_NUM1; outer++) {
        uint64_t c_hi = UINT64_MAX, c_lo = UINT64_MAX;
        uint64_t a_hi = 0, a_lo = 0, b_hi = 0, b_lo = 0;

        for (size_t j = FP_LIMBS; j-- > 0;) {
            uint64_t aw = a.limb[j], bw = b.limb[j];
            a_hi ^= (a_hi ^ aw) & c_hi;
            a_lo ^= (a_lo ^ aw) & c_lo;
            b_hi ^= (b_hi ^ bw) & c_hi;
            b_lo ^= (b_lo ^ bw) & c_lo;
            c_lo = c_hi;
            uint64_t mw = aw | bw;
            c_hi &= ((mw | (uint64_t)(0 - mw)) >> 63) - 1;
        }

        unsigned s = (unsigned)__builtin_clzll(a_hi | b_hi);
        uint64_t xa = (a_hi << s) | ((a_lo >> 1) >> (63 - s));
        uint64_t xb = (b_hi << s) | ((b_lo >> 1) >> (63 - s));
        xa = (xa & UINT64_C(0xffffffff80000000)) |
             (a.limb[0] & UINT64_C(0x7fffffff));
        xb = (xb & UINT64_C(0xffffffff80000000)) |
             (b.limb[0] & UINT64_C(0x7fffffff));
        xa ^= c_lo & (xa ^ a.limb[0]);
        xb ^= c_lo & (xb ^ b.limb[0]);

        /* First 29 inner iterations. */
        uint64_t fg0 = 1, fg1 = UINT64_C(1) << 32;
        for (unsigned k = 0; k < 29; k++) {
            uint64_t a_odd = (uint64_t)0 - (xa & 1);
            uint64_t d;
            unsigned char borrow = subborrow_u64(0, xa, xb, &d);
            uint64_t swap = a_odd & ((uint64_t)0 - (uint64_t)borrow);

            ls ^= swap & ((xa & xb) >> 1);

            uint64_t t = swap & (xa ^ xb);
            xa ^= t;
            xb ^= t;
            t = swap & (fg0 ^ fg1);
            fg0 ^= t;
            fg1 ^= t;

            xa -= a_odd & xb;
            fg0 -= a_odd & fg1;
            xa >>= 1;
            fg1 <<= 1;
            ls ^= (xb + 2) >> 2;
        }

        /* Recover the low words needed to perform two more iterations. */
        uint64_t fg0z = fg0 + UINT64_C(0x7fffffff7fffffff);
        uint64_t fg1z = fg1 + UINT64_C(0x7fffffff7fffffff);
        uint64_t f0 = (fg0z & UINT64_C(0xffffffff)) - UINT64_C(0x7fffffff);
        uint64_t g0 = (fg0z >> 32) - UINT64_C(0x7fffffff);
        uint64_t f1 = (fg1z & UINT64_C(0xffffffff)) - UINT64_C(0x7fffffff);
        uint64_t g1 = (fg1z >> 32) - UINT64_C(0x7fffffff);
        uint64_t a0 = (a.limb[0] * f0 + b.limb[0] * g0) >> 29;
        uint64_t b0 = (a.limb[0] * f1 + b.limb[0] * g1) >> 29;

        for (unsigned k = 0; k < 2; k++) {
            uint64_t a_odd = (uint64_t)0 - (xa & 1);
            uint64_t d;
            unsigned char borrow = subborrow_u64(0, xa, xb, &d);
            uint64_t swap = a_odd & ((uint64_t)0 - (uint64_t)borrow);

            ls ^= swap & ((a0 & b0) >> 1);

            uint64_t t = swap & (xa ^ xb);
            xa ^= t;
            xb ^= t;
            t = swap & (fg0 ^ fg1);
            fg0 ^= t;
            fg1 ^= t;
            t = swap & (a0 ^ b0);
            a0 ^= t;
            b0 ^= t;

            xa -= a_odd & xb;
            fg0 -= a_odd & fg1;
            a0 -= a_odd & b0;
            xa >>= 1;
            fg1 <<= 1;
            a0 >>= 1;
            ls ^= (b0 + 2) >> 2;
        }

        /* Propagate the 31-step transformation to the full operands. */
        fg0 += UINT64_C(0x7fffffff7fffffff);
        fg1 += UINT64_C(0x7fffffff7fffffff);
        f0 = (fg0 & UINT64_C(0xffffffff)) - UINT64_C(0x7fffffff);
        g0 = (fg0 >> 32) - UINT64_C(0x7fffffff);
        f1 = (fg1 & UINT64_C(0xffffffff)) - UINT64_C(0x7fffffff);
        g1 = (fg1 >> 32) - UINT64_C(0x7fffffff);

        fp_t na, nb;
        uint64_t nega = fp_lindiv31abs(&na, &a, &b, f0, g0);
        (void)fp_lindiv31abs(&nb, &a, &b, f1, g1);
        ls ^= nega & (nb.limb[0] >> 1);
        a = na;
        b = nb;
    }

    /* The remaining operands fit in one word. */
    uint64_t xa = a.limb[0];
    uint64_t xb = b.limb[0];
    for (size_t k = 0; k < FP_NUM2; k++) {
        uint64_t a_odd = (uint64_t)0 - (xa & 1);
        uint64_t d;
        unsigned char borrow = subborrow_u64(0, xa, xb, &d);
        uint64_t swap = a_odd & ((uint64_t)0 - (uint64_t)borrow);

        ls ^= swap & ((xa & xb) >> 1);

        uint64_t t = swap & (xa ^ xb);
        xa ^= t;
        xb ^= t;
        xa -= a_odd & xb;
        xa >>= 1;
        ls ^= (xb + 2) >> 2;
    }

    /* 0 -> 0, QR -> +1, QNR -> -1. */
    uint32_t r = 1u - (((uint32_t)ls & 1u) << 1);
    uint64_t z = 0;
    for (size_t i = 0; i < FP_LIMBS; i++)
        z |= x->limb[i];
    uint32_t nz = (uint32_t)((z | (uint64_t)(0 - z)) >> 63);
    r &= (uint32_t)0 - nz;
    return (int32_t)r;
}

uint32_t
fp_is_square(const fp_t *a) {
    int32_t val = fp_legendre(a);
    return ~(uint32_t)(val >> 31);
}
    
static void
fp_pow_pubexp(fp_t *out, const fp_t *a, const uint64_t e[FP_LIMBS])
{
    fp_t win[15];
    win[0] = *a;
    for (size_t i = 1; i < 8; i++) {
        size_t j = i * 2;
        fp_sqr(&win[j - 1], &win[i - 1]);
        fp_mul(&win[j], &win[j - 1], &win[0]);
    }

    fp_t t = { { 0 } };
    int started = 0;
    for (size_t i = FP_LIMBS; i-- > 0;) {
        uint64_t ew = e[i];
        for (unsigned j = 16; j-- > 0;) {
            unsigned c = (unsigned)((ew >> (j * 4)) & 0x0f);
            if (started)
                fp_n_sqr(&t, &t, 4);
            if (c != 0) {
                if (started)
                    fp_mul(&t, &t, &win[c - 1]);
                else {
                    t = win[c - 1];
                    started = 1;
                }
            }
        }
    }
    if (!started)
        t = FP_ONE;
    *out = t;
}

void
fp_sqrt(fp_t *a)
{
    fp_pow_pubexp(a, a, FP_SQRT_EXP);
}

void
fp_exp3div4(fp_t *out, const fp_t *a)
{
    fp_pow_pubexp(out, a, FP_P_MINUS_3_DIV_FOUR);
}

void
fp_div3(fp_t *out, const fp_t *a)
{
    fp_mul(out, a, &FP_THREE_INV);
}

static void
fp_decode_nocheck(fp_t *out, const uint8_t in[FP_ENCODED_BYTES])
{
    fp_t raw = { { 0 } };

    for (size_t i = 0; i < FP_LIMBS - 1; i++) {
        uint64_t w = 0;
        for (size_t j = 0; j < 8; j++)
            w |= (uint64_t)in[8 * i + j] << (8 * j);
        raw.limb[i] = w;
    }

    {
        const size_t last = FP_LIMBS - 1;
        const size_t last_bytes = FP_ENCODED_BYTES - 8 * (FP_LIMBS - 1);
        uint64_t w = 0;
        for (size_t j = 0; j < last_bytes; j++)
            w |= (uint64_t)in[8 * last + j] << (8 * j);
        raw.limb[last] = w;
    }

    *out = raw;
}

uint32_t
fp_decode(fp_t *out, const void *src)
{
    const uint8_t *in = src;
    fp_t raw;
    fp_decode_nocheck(&raw, in);

    uint64_t borrow = 0;
    for (size_t i = 0; i < FP_LIMBS; i++) {
        uint64_t d;
        borrow = subborrow_u64((unsigned char)borrow,
                                       raw.limb[i], FP_MODULUS[i], &d);
    }

    uint64_t mask = (uint64_t)0 - borrow;
    for (size_t i = 0; i < FP_LIMBS; i++)
        raw.limb[i] &= mask;

    fp_mul(out, &raw, &FP_R2_ELEM);
    return (uint32_t)mask;
}

void
fp_decode_reduce(fp_t *out, const void *src, size_t len)
{
    const uint8_t *in = src;
    fp_t t = { { 0 } };
    uint8_t tmp[FP_ENCODED_BYTES];

    if (len == 0) {
        *out = t;
        return;
    }

    /* Match Rust set_decode_reduce(): process fixed-size chunks MSB first. */
    size_t rem = len % FP_DECODE_REDUCE_CHUNK;
    if (rem == 0)
        rem = FP_DECODE_REDUCE_CHUNK;

    size_t pos = len - rem;
    memset(tmp, 0, sizeof(tmp));
    memcpy(tmp, in + pos, rem);
    fp_decode_nocheck(&t, tmp);

    while (pos != 0) {
        pos -= FP_DECODE_REDUCE_CHUNK;
        memset(tmp, 0, sizeof(tmp));
        memcpy(tmp, in + pos, FP_DECODE_REDUCE_CHUNK);

        fp_t d;
        fp_decode_nocheck(&d, tmp);
        fp_mul(&t, &t, &FP_TDEC_ELEM);
        fp_add(&t, &t, &d);
    }

    fp_mul(out, &t, &FP_R2_ELEM);
}

void
fp_encode(void *dst, const fp_t *x)
{
    uint8_t *out = dst;
    fp_t t = *x;
    fp_internal_reduce(&t);

    for (size_t i = 0; i < FP_LIMBS - 1; i++) {
        uint64_t w = t.limb[i];
        for (size_t j = 0; j < 8; j++) {
            out[8 * i + j] = (uint8_t)(w >> (8 * j));
        }
    }

    {
        const size_t last = FP_LIMBS - 1;
        const size_t last_bytes = FP_ENCODED_BYTES - 8 * (FP_LIMBS - 1);
        uint64_t w = t.limb[last];

        for (size_t j = 0; j < last_bytes; j++) {
            out[8 * last + j] = (uint8_t)(w >> (8 * j));
        }
    }
}
