set(SOURCE_FILES_NIKE_GENERIC_REF
    ${LVLX_DIR}/encode.c
    ${LVLX_DIR}/keygen.c
    ${LVLX_DIR}/exchange.c
)

add_library(${LIB_NIKE_${SVARIANT_UPPER}} STATIC ${SOURCE_FILES_NIKE_GENERIC_REF})
target_link_libraries(${LIB_NIKE_${SVARIANT_UPPER}} ${LIB_PRECOMP_${SVARIANT_UPPER}} ${LIB_GF_${SVARIANT_UPPER}} ${LIB_EC_${SVARIANT_UPPER}} ${LIB_WEIL_${SVARIANT_UPPER}} )
target_include_directories(${LIB_NIKE_${SVARIANT_UPPER}} PRIVATE ${INC_PUBLIC} ${INC_COMMON} ${INC_PRECOMP_${SVARIANT_UPPER}} ${INC_GF} ${INC_GF_${SVARIANT_UPPER}} ${INC_EC} ${INC_THETA} ${INC_WEIL} ${INC_NIKE})
target_compile_options(${LIB_NIKE_${SVARIANT_UPPER}} PRIVATE ${C_OPT_FLAGS})
target_compile_definitions(${LIB_NIKE_${SVARIANT_UPPER}} PUBLIC MIKE_VARIANT=${SVARIANT_LOWER})

add_subdirectory(test)
