#include "ec_isog.h"
#include "ec.h"
#include <constants.h>
#include "tools.h"
#include <assert.h>

void
ec_xDBL_A24(ec_xz_point_t *Q, const ec_xz_point_t *P, const ec_xz_point_t *A24)
{ // Doubling of a Montgomery point in projective coordinates (X:Z).
  // Input: projective Montgomery x-coordinates P = (XP:ZP), where xP=XP/ZP, and
  //        the Montgomery curve constants A24 = (A+2C:4C) (or A24 = (A+2C/4C:1) if normalized).
  // Output: projective Montgomery x-coordinates Q <- 2*P = (XQ:ZQ) such that x(2P)=XQ/ZQ.
    fp2_t t0, t1, t2;

    fp2_add(&t0, &P->x, &P->z);
    fp2_sqr(&t0, &t0);
    fp2_sub(&t1, &P->x, &P->z);
    fp2_sqr(&t1, &t1);
    fp2_sub(&t2, &t0, &t1);
    // if (!A24_normalized)
    fp2_mul(&t1, &t1, &A24->z);
    fp2_mul(&Q->x, &t0, &t1);
    fp2_mul(&t0, &t2, &A24->x);
    fp2_add(&t0, &t0, &t1);
    fp2_mul(&Q->z, &t0, &t2);
}

uint32_t
ec_xz_is_two_torsion(const ec_xz_point_t *P, const ec_curve_t *E)
{
    if (ec_xz_is_zero(P))
        return 0;

    uint32_t x_is_zero, tmp_is_zero;
    fp2_t t0, t1, t2;
    fp2_add(&t0, &P->x, &P->z);
    fp2_sqr(&t0, &t0);
    fp2_sub(&t1, &P->x, &P->z);
    fp2_sqr(&t1, &t1);
    fp2_sub(&t2, &t0, &t1);
    fp2_add(&t1, &t0, &t1);
    fp2_mul(&t2, &t2, &E->A);
    // fp2_mul(&t1, &t1, &E->C);
    fp2_add(&t1, &t1, &t1);
    fp2_add(&t0, &t1, &t2); // 4 (CX^2+CZ^2+AXZ)

    x_is_zero = fp2_is_zero(&P->x);
    tmp_is_zero = fp2_is_zero(&t0);

    // two torsion if x or x^2 + Ax + 1 is zero
    return x_is_zero | tmp_is_zero;
}

uint32_t
ec_xz_is_four_torsion(const ec_xz_point_t *P, const ec_curve_t *E)
{
    ec_xz_point_t test;
    ec_xz_point_t A24;
    // modified since A24 is now int not point
    ec_curve_to_A24(&A24, E);
    ec_xz_normalize(&A24);
    ec_xDBL_A24(&test, P, &A24);
    return ec_xz_is_two_torsion(&test, E);
}

// Degree-4 isogeny with kernel generated by P such that [2]P != (0 ,0)
// Outputs the curve coefficient in the form A24=(A+2C:4C)
void
ec_iso_xisog_4(ec_kps4_t *kps, ec_xz_point_t *B, const ec_xz_point_t P)
{
    fp2_t t1, t2, t3, t4;

    fp2_sqr(&t1, &P.x);
    fp2_sqr(&t2, &P.z);

    fp2_add(&t3, &t2, &t1);
    fp2_sub(&t4, &t2, &t1);
    fp2_mul(&B->x, &t3, &t4);
    fp2_sqr(&B->z, &t2);

    // Constants for xeval_4
    fp2_add(&kps->K[2], &P.x, &P.z);
    fp2_sub(&kps->K[1], &P.x, &P.z);
    fp2_add(&t2, &t2, &t2);
    fp2_add(&kps->K[0], &t2, &t2);
}

// Degree-4 isogeny evaluation with kernel generated by P such that [2]P != (0, 0)
void
ec_iso_xeval_4(ec_xz_point_t *R, const ec_xz_point_t *Q, const int lenQ, const ec_kps4_t *kps)
{
    fp2_t t0, t1;

    for (int i = 0; i < lenQ; i++) {
        fp2_add(&t0, &Q[i].x, &Q[i].z);
        fp2_sub(&t1, &Q[i].x, &Q[i].z);
        fp2_mul(&(R[i].x), &t0, &kps->K[1]);
        fp2_mul(&(R[i].z), &t1, &kps->K[2]);
        fp2_mul(&t0, &t0, &t1);
        fp2_mul(&t0, &t0, &kps->K[0]);
        fp2_add(&t1, &(R[i].x), &(R[i].z));
        fp2_sub(&(R[i].z), &(R[i].x), &(R[i].z));
        fp2_sqr(&t1, &t1);
        fp2_sqr(&(R[i].z), &(R[i].z));
        fp2_add(&(R[i].x), &t0, &t1);
        fp2_sub(&t0, &t0, &(R[i].z));
        fp2_mul(&(R[i].x), &(R[i].x), &t1);
        fp2_mul(&(R[i].z), &(R[i].z), &t0);
    }
}

int
ec_xz_order_even2(const ec_xz_point_t *P, ec_curve_t *curve)
{
    ec_xz_point_t Q, R;
    fp2_copy(&Q.x, &P->x);
    fp2_copy(&Q.z, &P->z);
    ec_xMUL(&Q, &R, &Q, TORSION_ODD, 10, curve);
    int order = 1;
    while (!ec_xz_is_two_torsion(&Q, curve)) {
        ec_xDBL(&Q, &Q, curve);
        order = order + 1;
    }
    return (order);
}

// since we use degree 4 isogeny steps, we only allow 2^e-isogenies with even e
uint32_t
ec_iso_isogeny_2chain_with_strategy(fp2_t *imageA,
                                    const ec_curve_t *curve,
                                    const ec_xz_point_t *kernel,
                                    const int isog_len,
                                    ec_xz_point_t *to_eval,
                                    int to_eval_len,
                                    int normalize)
{
    ec_xz_point_t A24, s;
    ec_curve_to_A24(&A24, curve);
    // ec_copy_xz_point(&A24, &curve->A24);

    int space = 1;
    for (int i = 1; i < isog_len; i *= 2)
        ++space;

    // Stack of remaining kernel points and their associated orders
    ec_xz_point_t splits[space];
    uint16_t todo[space];
    splits[0] = *kernel;
    todo[0] = isog_len;

    // only 2^e-isogenies with e even are allowed
    assert(isog_len % 2 == 0);

    int current = 0; // Pointer to current top of stack

    // Chain of 4-isogenies
    for (int j = 0; j < isog_len / 2 - 1; ++j) {
        assert(current >= 0);
        assert(todo[current] >= 1);
        // Get the next point of order 4
        while (todo[current] != 2) {
            assert(todo[current] >= 3);
            // A new split will be added
            ++current;
            assert(current < space);
            // We set the seed of the new split to be computed and saved
            ec_copy_xz_point(&splits[current], &splits[current - 1]);
            // if we copied from the very first element, then we perform one additional doubling
            unsigned num_dbls = todo[current - 1] / 4 * 2 + todo[current - 1] % 2;
            todo[current] = todo[current - 1] - num_dbls;
            while (num_dbls--) {
                ec_copy_xz_point(&s, &splits[current]);
                ec_xDBL_A24(&splits[current], &s, &A24);
            }
        }

#ifndef NDEBUG
        if (j == 0) {
            assert(fp2_is_one(&A24.z));
            if (!ec_xz_is_four_torsion(&splits[current], curve)) {
                printf("Incorrect kernel order\n");
                assert(false);
            }

            ec_xz_point_t T;
            ec_xDBL_A24(&T, &splits[current], &A24);
            if (fp2_is_zero(&T.x)) {
                debug_print("Kernel above a canonical 4 torsion point !\n");
                assert(false); // special isogenies not allowed
            }
        } else {
            assert(todo[current] == 2);
            if (fp2_is_zero(&splits[current].z))
                debug_print("splitting point z coordinate is unexpectedly zero");

            ec_xz_point_t test;
            ec_xDBL_A24(&test, &splits[current], &A24);
            if (fp2_is_zero(&test.z))
                debug_print("z coordinate is unexpectedly zero before doubling");
            ec_xDBL_A24(&test, &test, &A24);
            if (!fp2_is_zero(&test.z))
                debug_print("z coordinate is unexpectedly not zero after doubling");
        }
#endif

        // Evaluate 4-isogeny
        ec_kps4_t kps4;
        ec_iso_xisog_4(&kps4, &A24, splits[current]);
        ec_iso_xeval_4(splits, splits, current, &kps4);
        if (to_eval_len != 0) {
            ec_iso_xeval_4(to_eval, to_eval, to_eval_len, &kps4);
        }
        for (int i = 0; i < current; ++i)
            todo[i] -= 2;

        --current;
    }
    assert(isog_len % 2 ? !current : current == 0);

    ec_A24_to_curve_A(imageA, &A24);

// check 4 point is above zero
#ifndef NDEBUG
    ec_curve_t E;
    ec_curve_init_from_A(&E, imageA);
    assert(ec_xz_is_four_torsion(&splits[current], &E));
#endif
    if (normalize) {
        if (!ec_normalize_montgomery(imageA, &splits[current], normalize)) {
            printf("Normalization failed\n");
            return (-1);
        }
    }
    return 0;
}

uint32_t
ec_iso_isogeny_2chain(fp2_t *imageA, ec_isog_even_t *phi, int normalize)
{
    return ec_iso_isogeny_2chain_with_strategy(imageA, &phi->curve, &phi->kernel, phi->length, NULL, 0, normalize);
}
