#define SECURITY_BITS 320
#define FP_ENCODED_BYTES 96
#define FP2_ENCODED_BYTES 192
#define EC_CURVE_ENCODED_BYTES 192
#define PUBLICKEY_BYTES 192
#define SECRETKEY_BYTES 71
#define SECRETKEY_BITS 564
#define HD_MARGIN 2
#define SECRETKEY_CHAIN_LENGTH 564
#define SHARED_BYTES 32
#if RADIX == 32
#define SECRETKEY_WORDS 18
#elif RADIX == 64
#define SECRETKEY_WORDS 9
#endif

