#define SECURITY_BITS 128
#define FP_ENCODED_BYTES 48
#define FP2_ENCODED_BYTES 96
#define EC_CURVE_ENCODED_BYTES 96
#define PUBLICKEY_BYTES 96
#define SECRETKEY_BYTES 47
#define SECRETKEY_BITS 372
#define HD_MARGIN 2
#define SECRETKEY_CHAIN_LENGTH 372
#define SHARED_BYTES 32
#if RADIX == 32
#define SECRETKEY_WORDS 12
#elif RADIX == 64
#define SECRETKEY_WORDS 6
#endif

