#define SECURITY_BITS 192
#define FP_ENCODED_BYTES 72
#define FP2_ENCODED_BYTES 144
#define EC_CURVE_ENCODED_BYTES 144
#define PUBLICKEY_BYTES 144
#define SECRETKEY_BYTES 43
#define SECRETKEY_BITS 340
#define HD_MARGIN 2
#define SECRETKEY_CHAIN_LENGTH 340
#define SHARED_BYTES 32
#if RADIX == 32
#define SECRETKEY_WORDS 11
#elif RADIX == 64
#define SECRETKEY_WORDS 6
#endif

