#define SECURITY_BITS 256
#define FP_ENCODED_BYTES 80
#define FP2_ENCODED_BYTES 160
#define EC_CURVE_ENCODED_BYTES 160
#define PUBLICKEY_BYTES 160
#define SECRETKEY_BYTES 57
#define SECRETKEY_BITS 452
#define HD_MARGIN 2
#define SECRETKEY_CHAIN_LENGTH 452
#define SHARED_BYTES 32
#if RADIX == 32
#define SECRETKEY_WORDS 15
#elif RADIX == 64
#define SECRETKEY_WORDS 8
#endif

